# Generated by Django 5.0.3 on 2024-04-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_drf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id_carrito', models.IntegerField(db_column='ID_Carrito', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'carrito_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.IntegerField(db_column='ID_Ciudad', primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.IntegerField(db_column='ID_Comentario', primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
            ],
            options={
                'db_table': 'comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('num_identificacion', models.IntegerField(db_column='NUM_IDENTIFICACION', primary_key=True, serialize=False)),
                ('celular', models.CharField(blank=True, db_column='CELULAR', max_length=20, null=True)),
                ('correo', models.CharField(blank=True, db_column='CORREO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'contactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.IntegerField(db_column='ID_Departamento', primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle', models.IntegerField(db_column='ID_Detalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('total_productos', models.IntegerField(blank=True, db_column='Total_Productos', null=True)),
            ],
            options={
                'db_table': 'detalle_carrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilios',
            fields=[
                ('id_domicilio', models.IntegerField(db_column='ID_Domicilio', primary_key=True, serialize=False)),
                ('valor_domicilio', models.DecimalField(blank=True, db_column='Valor_Domicilio', decimal_places=2, max_digits=10, null=True)),
                ('fecha_entrega', models.DateTimeField(db_column='Fecha_Entrega')),
                ('observaciones_domiciliario', models.TextField(blank=True, db_column='Observaciones_Domiciliario', null=True)),
                ('observaciones_cliente', models.TextField(blank=True, db_column='Observaciones_Cliente', null=True)),
                ('calificacion', models.IntegerField(blank=True, db_column='Calificacion', null=True)),
            ],
            options={
                'db_table': 'domicilios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(db_column='ID_Estado', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionarproductosCategorias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gestionarproductos_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionarproductosImagenesproducto',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'gestionarproductos_imagenesproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionarproductosMarcas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gestionarproductos_marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionarproductosProductos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'gestionarproductos_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionusuariosUsuarios',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='Correo_Electronico', max_length=100, null=True)),
                ('contrase_a_encriptada', models.CharField(blank=True, db_column='Contrase▒a_Encriptada', max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=255, null=True)),
            ],
            options={
                'db_table': 'gestionusuarios_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'imagenes_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexUsuarios',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='Correo_Electronico', max_length=100, null=True)),
                ('contrase_a_encriptada', models.CharField(blank=True, db_column='Contrase▒a_Encriptada', max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=255, null=True)),
            ],
            options={
                'db_table': 'index_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediosPago',
            fields=[
                ('id_mediopago', models.IntegerField(db_column='ID_MedioPago', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'medios_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('nit', models.IntegerField(db_column='NIT', primary_key=True, serialize=False)),
                ('razon_social', models.CharField(blank=True, db_column='RAZON_SOCIAL', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='TELEFONO', max_length=20, null=True)),
                ('correo', models.CharField(blank=True, db_column='CORREO', max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, db_column='DIRECCION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id_respuesta', models.IntegerField(db_column='ID_Respuesta', primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, db_column='Respuesta', null=True)),
            ],
            options={
                'db_table': 'respuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(db_column='ID_Rol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id_tipo', models.IntegerField(db_column='ID_Tipo', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipo_identificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, db_column='Correo_Electronico', max_length=100, null=True)),
                ('contrasena_encriptada', models.CharField(blank=True, db_column='contrasena_encriptada', max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(db_column='Fecha_Registro')),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(db_column='ID_Venta', primary_key=True, serialize=False)),
                ('total_compra', models.DecimalField(blank=True, db_column='Total_Compra', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedoresProductos',
            fields=[
                ('proveedor', models.OneToOneField(db_column='PROVEEDOR', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api_drf.proveedores')),
            ],
            options={
                'db_table': 'proveedores_productos',
                'managed': False,
            },
        ),
    ]
